version: '2'
services:  
  predictionio-engine:
    image: opengate/predictionio:latest
    depends_on:     
     - predictionio-database
    ports:
     - 8000:8000
     - 7070:7070
     - 9000:9000
    restart: always
  predictionio-database:
    image: postgres:9.4
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=predictionio
     - POSTGRES_DB=postgresql
     - PGDATA=/var/lib/postgresql/data
    ports:
     - 5432:5432
    restart: always