version: '2'
services:  
  predictionio:
    image: opengate/predictionio:latest
    depends_on:     
     - postgresql
    environment:
    - SPARK_MASTER_IP=172.20.1.137
    - POSTGRESQL_DATABASE=postgresql
    ports:
     - 8000:8000
     - 7070:7070
     - 9000:9000
    volumes:
     - ./experiments:/opt/PredictionIO
    restart: always
  postgresql:
    image: postgres:9.4
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=predictionio
     - POSTGRES_DB=postgresql
     - PGDATA=/var/lib/postgresql/data
    volumes:
     - ../postgresql/data:/var/lib/postgresql/data
    ports:
     - 5432:5432
    restart: always